"""

Revision ID: 879b79e2d169
Revises: 
Create Date: 2026-07-03 17:23:06.585553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879b79e2d169'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_projects',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('travel_places',
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_visited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['travel_projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id'),
    sa.UniqueConstraint('project_id', 'external_id', name='uq_project_external_place')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_places')
    op.drop_table('travel_projects')
    # ### end Alembic commands ###
